const sS=v=>String(v==null?'':v).trim(),sN=v=>Number.isFinite(Number(v))?Number(v):0;
export const normalizeDevicePlatform=ua=>{const r=sS(ua||navigator.userAgent);return /iPhone|iPad/i.test(r)?'ios':(/Android/i.test(r)?'android':'web');};
export const normalizeDeviceClass=({platform='web',rawClass=''}={})=>{const r=sS(rawClass).toLowerCase();if(['iphone','ipad','android','desktop','tablet'].includes(r))return r.charAt(0).toUpperCase()+r.slice(1);return platform==='ios'?'iPhone':(platform==='android'?'Android':'Desktop');};
export const detectBrowserName=ua=>{const r=sS(ua||navigator.userAgent);return /YaBrowser\/([\d.]+)/.test(r)?'Яндекс Браузер':(/OPR\/|Opera\//.test(r)?'Opera':(/Edg\//.test(r)?'Edge':(/Chrome\//.test(r)&&!/Edg\//.test(r)?'Chrome':(/Safari\//.test(r)&&!/Chrome\//.test(r)?'Safari':(/Firefox\//.test(r)?'Firefox':'Browser')))));};
export const detectOsName=ua=>{const r=sS(ua||navigator.userAgent);return /iPhone/i.test(r)?{os:'iPhone',osIcon:'📱'}:(/iPad/i.test(r)?{os:'iPad',osIcon:'📱'}:(/Android/i.test(r)?{os:'Android',osIcon:'📱'}:(/Mac OS X|Macintosh/i.test(r)?{os:'macOS',osIcon:'🖥'}:(/Windows/i.test(r)?{os:'Windows',osIcon:'🖥'}:(/Linux/i.test(r)?{os:'Linux',osIcon:'🖥'}:{os:'Unknown OS',osIcon:'💻'})))));};
export const getDefaultDeviceLabel=({platform='web',deviceNumber=1,savedLabel=''}={})=>sS(savedLabel)||`Моё устройство №${Math.max(1,sN(deviceNumber)||1)}`;
export const detectCurrentDeviceProfile=({registry=[],savedLabel=''}={})=>{const ua=navigator.userAgent,platform=normalizeDevicePlatform(ua),{os,osIcon}=detectOsName(ua),browser=detectBrowserName(ua),deviceNumber=(Array.isArray(registry)?registry.length:0)+1;return{os,osIcon,browser,platform,class:normalizeDeviceClass({platform}),screen:`${window.screen.width||0}×${window.screen.height||0}`,lang:navigator.language||'',userAgent:ua,label:getDefaultDeviceLabel({platform,deviceNumber,savedLabel}),deviceNumber,lastActive:new Date().toLocaleDateString('ru-RU')};};
export const getSystemInstallDateLabel=()=>{const t=sN(localStorage.getItem('app:first-install-ts')||0);return t>0?new Date(t).toLocaleDateString('ru-RU'):'—';};
export default{normalizeDevicePlatform,normalizeDeviceClass,detectBrowserName,detectOsName,getDefaultDeviceLabel,detectCurrentDeviceProfile,getSystemInstallDateLabel};
