import { safeNum } from '../../analytics/backup-summary.js'; import { describeEventForUi } from '../../analytics/event-contract.js'; import { esc, renderCloudSectionCard, fmtDateTime } from './cloud-card-renderers.js';
const jp = (r, f = []) => { try{return JSON.parse(r||'');}catch{return f;} }, aF = r => new Set((Array.isArray(r)?r:[]).filter(x=>x?.uid&&!x.inactiveAt&&!x.deletedAt).map(x=>String(x.uid))), aP = r => new Map((Array.isArray(r)?r:[]).filter(x=>x?.id&&!x.deletedAt).map(x=>[String(x.id),x]));
const lR = () => ({ fav:jp(localStorage.getItem('__favorites_v2__')||'[]',[]), pl:jp(localStorage.getItem('sc3:playlists')||'[]',[]) }), cR = b => ({ fav:jp(b?.data?.localStorage?.['__favorites_v2__']||'[]',[]), pl:jp(b?.data?.localStorage?.['sc3:playlists']||'[]',[]) });
const row = (n, l, c, h = '') => { const d=safeNum(c)-safeNum(l), s=d>0?`+${d}`:String(d), cls=d>0?'#81c784':(d<0?'#ffb74d':'#9db7dd'); return `<div style="display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-bottom:1px solid rgba(255,255,255,.05)"><div style="color:#eaf2ff;font-size:12px">${esc(n)}${h?`<div style="color:#667;font-size:10px;margin-top:2px">${esc(h)}</div>`:''}</div><div style="font-size:12px;font-weight:900;color:${cls};white-space:nowrap">${safeNum(l)} → ${safeNum(c)} <span style="opacity:.75">(${esc(s)})</span></div></div>`; };
const exactDiff = b => { const l=lR(), c=cR(b), lf=aF(l.fav), cf=aF(c.fav), lp=aP(l.pl), cp=aP(c.pl); return { lf,cf,lp,cp, favCloudOnly:[...cf].filter(x=>!lf.has(x)).length, favLocalOnly:[...lf].filter(x=>!cf.has(x)).length, plCloudOnly:[...cp.keys()].filter(x=>!lp.has(x)).length, plLocalOnly:[...lp.keys()].filter(x=>!cp.has(x)).length, deletedCloud:(Array.isArray(c.pl)?c.pl:[]).filter(x=>x?.deletedAt).length }; };
const renderEventExample = ev => { const v=describeEventForUi(ev), t=[v.title,ev?.uid||''].filter(Boolean).join(' · '); return `<div style="padding:6px 0;border-bottom:1px solid rgba(255,255,255,.04)"><div style="font-size:11px;color:#eaf2ff">${esc(v.icon)} ${esc(t)}</div><div style="font-size:10px;color:#7f93b5;margin-top:1px">${esc(fmtDateTime(ev?.timestamp))}${v.desc?` · ${esc(v.desc)}`:''}</div></div>`; };
const renderBranchExamples = br => { if(!br)return ''; const loc=(br.localOnlyEvents||[]).slice(-3).reverse(), cld=(br.cloudOnlyEvents||[]).slice(-3).reverse(); return `<div style="margin-top:10px;display:grid;grid-template-columns:1fr;gap:8px"><div style="font-size:11px;color:#9db7dd;line-height:1.45">Ветки событий: <b>${esc(br.state)}</b><br>Только локально: <b>${br.localOnlyCount}</b> · только в облаке: <b>${br.cloudOnlyCount}</b> · пересечение: <b>${br.overlapCount}</b></div>${loc.length?`<div><div style="font-size:10px;font-weight:900;color:#ffb74d;text-transform:uppercase;letter-spacing:.7px">Последние локальные</div>${loc.map(renderEventExample).join('')}</div>`:''}${cld.length?`<div><div style="font-size:10px;font-weight:900;color:#8ab8fd;text-transform:uppercase;letter-spacing:.7px">Последние из облака</div>${cld.map(renderEventExample).join('')}</div>`:''}</div>`; };
export const renderRestoreDiffHtml = ({ backup: b, localSummary: lS, cloudSummary: cS, devices: dv = [], branch: br = null, deviceSettingsState: dSS = '' } = {}) => { const e=b?exactDiff(b):null, cEC=safeNum(cS?.eventCount||b?.data?.eventLog?.warm?.length||0), cDC=safeNum(cS?.devicesCount||dv.length||0); const pH=e?`<div style="margin-top:9px;color:#9db7dd;font-size:11px;line-height:1.45">Точный diff: ⭐ из облака +${e.favCloudOnly}, локальных ⭐ +${e.favLocalOnly}; плейлистов из облака +${e.plCloudOnly}, локальных плейлистов +${e.plLocalOnly}.${dSS?`<br>Device settings: <b>${esc(dSS)}</b>`:''}</div>`:''; return renderCloudSectionCard({ title:'Что будет объединено', style:'margin:12px 0', body:`${row('Уровень',lS?.level||1,cS?.level||1,'не понижается')}${row('XP',lS?.xp||0,cS?.xp||0,'берётся максимум')}${row('Достижения',lS?.achievementsCount||0,cS?.achievementsCount||0,'unlock-time сохраняется')}${row('Избранное',e?e.lf.size:lS?.favoritesCount||0,e?e.cf.size:cS?.favoritesCount||0,'active ⭐ имеет приоритет')}${row('Плейлисты',e?e.lp.size:lS?.playlistsCount||0,e?e.cp.size:cS?.playlistsCount||0,'удаления идут через корзину')}${row('События журнала',lS?.eventCount||0,cEC,'merge по eventId')}${row('Устройства',lS?.devicesCount||0,cDC,'выбор device settings вручную')}${pH}${renderBranchExamples(br)}${e?.deletedCloud?`<div style="margin-top:8px;color:#ffb74d;font-size:11px">В облаке есть удалённые плейлисты в корзине: <b>${e.deletedCloud}</b>.</div>`:''}`}); };
export default { renderRestoreDiffHtml };
