/** cache-db.js — IndexedDB-хранилище для offline-кэша. Stores: 'audio', 'trackMeta', 'global'. Optimized: Fixed OOM memory leak in blob checks, drastically reduced boilerplate. */
const DB_NAME = 'offlineCache', DB_VERSION = 2; let _db = null;
export const openDB = () => _db ? Promise.resolve(_db) : window.Utils.func.memoAsyncOnce('offline:cache-db:open', () => new Promise((res, rej) => { const req = indexedDB.open(DB_NAME, DB_VERSION); req.onupgradeneeded = e => { const db = e.target.result; if (!db.objectStoreNames.contains('audio')) db.createObjectStore('audio', { keyPath: ['uid', 'quality'] }); const ms = db.objectStoreNames.contains('trackMeta') ? e.target.transaction.objectStore('trackMeta') : db.createObjectStore('trackMeta', { keyPath: 'uid' }); if (!ms.indexNames.contains('type')) ms.createIndex('type', 'type', { unique: false }); if (!ms.indexNames.contains('cloudExpiresAt')) ms.createIndex('cloudExpiresAt', 'cloudExpiresAt', { unique: false }); if (!db.objectStoreNames.contains('global')) db.createObjectStore('global', { keyPath: 'key' }); }; req.onsuccess = () => res(_db = req.result); req.onerror = () => rej(req.error); }));
const db = () => { if (!_db) throw new Error('cache-db not opened.'); return _db; };
const read = (s, fn) => new Promise((res, rej) => { const r = fn(db().transaction(s, 'readonly').objectStore(s)); r.onsuccess = () => res(r.result); r.onerror = () => rej(r.error); });
const write = (s, fn) => new Promise((res, rej) => { const tx = db().transaction(s, 'readwrite'); fn(tx.objectStore(s)); tx.oncomplete = () => res(true); tx.onerror = () => rej(tx.error); });
export const setAudioBlob = (uid, q, blob) => write('audio', s => s.put({ uid, quality: String(q) === 'lo' ? 'lo' : 'hi', blob }));
export const getAudioBlob = async (uid, q) => (await read('audio', s => s.get([uid, q])))?.blob || null;
export const deleteAudio = uid => write('audio', s => { s.delete([uid, 'hi']); s.delete([uid, 'lo']); });
export const deleteAudioVariant = (uid, q) => write('audio', s => s.delete([uid, q]));
export const hasAudioForUid = async uid => !!(await read('audio', s => s.count([uid, 'hi']))) || !!(await read('audio', s => s.count([uid, 'lo'])));
export const getStoredVariant = async uid => (await read('audio', s => s.count([uid, 'hi']))) ? 'hi' : ((await read('audio', s => s.count([uid, 'lo']))) ? 'lo' : null);
export const setTrackMeta = (uid, meta) => write('trackMeta', s => s.put({ ...meta, uid }));
export const getTrackMeta = uid => read('trackMeta', s => s.get(uid));
export const updateTrackMeta = async (uid, u) => setTrackMeta(uid, { ...((await getTrackMeta(uid)) || {}), ...u, uid });
export const deleteTrackMeta = uid => write('trackMeta', s => s.delete(uid));
export const getAllTrackMetas = async () => (await read('trackMeta', s => s.getAll())) || [];
export const deleteTrackCache = async uid => { await deleteAudio(uid); await deleteTrackMeta(uid); };
export const getGlobal = k => read('global', s => s.get(String(k)));
export const setGlobal = (k, v) => write('global', s => s.put({ key: String(k), value: v }));
export const estimateUsage = async () => { try { if (navigator.storage?.estimate) { const e = await navigator.storage.estimate(); return { used: e.usage || 0, quota: e.quota || 0, free: Math.max(0, (e.quota || 0) - (e.usage || 0)) }; } } catch {} return { used: 0, quota: 524288000, free: 524288000 }; };
