export const safeNum = v => Number.isFinite(Number(v)) ? Number(v) : 0;
export const safeString = v => String(v == null ? '' : v).trim();
export const safeJsonParse = (r, f = null) => { try { return JSON.parse(r); } catch { return f; } };

export const getRichnessScore = (s = {}) => safeNum(s.level)*1000 + safeNum(s.xp) + safeNum(s.achievementsCount)*250 + safeNum(s.favoritesCount)*40 + safeNum(s.playlistsCount)*60 + safeNum(s.statsCount)*6 + safeNum(s.eventCount)*2 + safeNum(s.devicesCount)*25 + safeNum(s.deviceStableCount)*30;

export const compareLocalVsCloud = (l, c) => { const lTs=safeNum(l?.timestamp), cTs=safeNum(c?.timestamp), lSc=getRichnessScore(l), cSc=getRichnessScore(c), sDf=cSc-lSc, tDf=cTs-lTs; if(!c||(!cTs&&cSc===0)) return{state:'no_cloud',localTs:lTs,cloudTs:cTs,localScore:lSc,cloudScore:cSc,scoreDiff:sDf,tsDiff:tDf}; if(lTs===0&&lSc<=1200&&cSc>0) return{state:'cloud_richer_new_device',localTs:lTs,cloudTs:cTs,localScore:lSc,cloudScore:cSc,scoreDiff:sDf,tsDiff:tDf}; if(cTs>lTs&&cSc>=lSc) return{state:'cloud_richer',localTs:lTs,cloudTs:cTs,localScore:lSc,cloudScore:cSc,scoreDiff:sDf,tsDiff:tDf}; if(lTs>cTs&&lSc>=cSc) return{state:'local_richer',localTs:lTs,cloudTs:cTs,localScore:lSc,cloudScore:cSc,scoreDiff:sDf,tsDiff:tDf}; if(Math.abs(tDf)<120000&&Math.abs(sDf)<300) return{state:'equivalent',localTs:lTs,cloudTs:cTs,localScore:lSc,cloudScore:cSc,scoreDiff:sDf,tsDiff:tDf}; if(cSc>lSc&&cTs>=lTs) return{state:'cloud_probably_richer',localTs:lTs,cloudTs:cTs,localScore:lSc,cloudScore:cSc,scoreDiff:sDf,tsDiff:tDf}; if(lSc>cSc&&lTs>=cTs) return{state:'local_probably_richer',localTs:lTs,cloudTs:cTs,localScore:lSc,cloudScore:cSc,scoreDiff:sDf,tsDiff:tDf}; return{state:'conflict',localTs:lTs,cloudTs:cTs,localScore:lSc,cloudScore:cSc,scoreDiff:sDf,tsDiff:tDf}; };

export const getLocalBackupUiSnapshot = (p) => { try { const f=safeJsonParse(localStorage.getItem('__favorites_v2__'),[]), pl=safeJsonParse(localStorage.getItem('sc3:playlists'),[]), r=window.DeviceRegistry?.getDeviceRegistry?.() || safeJsonParse(localStorage.getItem('backup:device_registry:v1'),[]) || [], a=window.achievementEngine; return { appVersion:window.APP_CONFIG?.APP_VERSION||'unknown', timestamp:safeNum(localStorage.getItem('yandex:last_backup_local_ts')), favoritesCount:Array.isArray(f)?f.filter(i=>!i?.inactiveAt).length:0, playlistsCount:Array.isArray(pl)?pl.length:0, profileName:p?.name||'Слушатель', level:safeNum(a?.profile?.level||1), xp:safeNum(a?.profile?.xp||0), achievementsCount:Object.keys(a?.unlocked||{}).length, devicesCount:Array.isArray(r)?r.length:0, deviceStableCount:window.DeviceRegistry?.countDeviceStableIds?.(r) || new Set((Array.isArray(r)?r:[]).map(d=>safeString(d?.deviceStableId)).filter(Boolean)).size }; } catch { return { appVersion:window.APP_CONFIG?.APP_VERSION||'unknown', timestamp:safeNum(localStorage.getItem('yandex:last_backup_local_ts')), favoritesCount:0, playlistsCount:0, profileName:p?.name||'Слушатель', level:safeNum(window.achievementEngine?.profile?.level||1), xp:safeNum(window.achievementEngine?.profile?.xp||0), achievementsCount:Object.keys(window.achievementEngine?.unlocked||{}).length, devicesCount:0, deviceStableCount:0 }; } };

export const getBackupCompareLabel = (l, c) => c ? ({no_cloud:'Облачная копия отсутствует',cloud_richer_new_device:'Облако выглядит как основной источник для нового устройства',cloud_richer:'Облако богаче и новее локального профиля',cloud_probably_richer:'Облако вероятно богаче локального профиля',local_richer:'Локальные данные богаче облачной копии',local_probably_richer:'Локальный профиль вероятно богаче облачного',equivalent:'Локальная и облачная копии практически эквивалентны',conflict:'Есть смешанные признаки: нужна ручная проверка'})[compareLocalVsCloud(l||{},c||{}).state] || 'Сравнение недоступно' : 'Нет данных о копии';

export default { safeNum, safeString, safeJsonParse, getRichnessScore, compareLocalVsCloud, getLocalBackupUiSnapshot, getBackupCompareLabel };
