// scripts/analytics/backup-vault.js
// UID.003_(Event log truth)_(держать backup честным и пересчитываемым)_(backup должен оставаться event-log-centric) // UID.073_(Hybrid sync orchestrator)_(подготовить backup как transport-слой для multi-provider sync)_(future orchestration жить отдельно от vault) // UID.089_(Future MetaDB stores)_(расширить backup listener/provider/recommendation/collection state)_(когда intel stores начнут наполняться, vault должен включить их без ломки формата) // UID.099_(Multi-device sync model)_(готовить deterministic merge без дублей)_(backup должен знать owner/devices/revision) // UID.100_(Backup snapshot as life capsule)_(сделать один канонический файл пользователя)_(manual/cloud backup используют один и тот же формат)
import DeviceRegistry from './device-registry.js';
import { normalizeCloudBackupMeta } from './cloud-contract.js';
import { buildFullBackupObject, buildDeviceSettingsObject } from './backup-builders.js';
import { applyBackupImportObject, applyDeviceSettingsObject } from './backup-importers.js';

export class BackupVault {
  static async buildBackupObject() { return buildFullBackupObject(); }
  static async buildDeviceSettingsObject() { return buildDeviceSettingsObject(); }
  static async importBackupObject(backup, mode = 'all') {
    if (!backup || typeof backup !== 'object') throw new Error('invalid_backup_object');
    await applyBackupImportObject(backup, mode);
    return true;
  }
  static async importDeviceSettingsObject(device, options = {}) { return applyDeviceSettingsObject(device, options); }
  static summarizeBackupObject(b) { const ls=b?.data?.localStorage||{}, f=(()=>{try{return JSON.parse(ls['__favorites_v2__']||'[]');}catch{return[];}})(), p=(()=>{try{return JSON.parse(ls['sc3:playlists']||'[]');}catch{return[];}})(), dv=Array.isArray(b?.devices)?DeviceRegistry.normalizeDeviceRegistry(b.devices):[]; return normalizeCloudBackupMeta({ timestamp:Number(b?.revision?.timestamp||b?.createdAt||0), appVersion:String(b?.revision?.appVersion||'unknown'), statsCount:Array.isArray(b?.data?.stats)?b.data.stats.filter(x=>x?.uid&&x.uid!=='global').length:0, eventCount:Number(b?.data?.eventArchive?.eventCountFull||b?.data?.eventArchive?.eventCount||0)||(Array.isArray(b?.data?.eventLog?.warm)?b.data.eventLog.warm.length:0), achievementsCount:Object.keys(b?.data?.achievements||{}).length, favoritesCount:Array.isArray(f)?f.filter(x=>!x?.inactiveAt&&!x?.deletedAt).length:0, playlistsCount:Array.isArray(p)?p.filter(x=>!x?.deletedAt).length:0, profileName:String(b?.data?.userProfile?.name||'Слушатель'), ownerYandexId:String(b?.identity?.ownerYandexId||''), devicesCount:dv.length, deviceStableCount:DeviceRegistry.countDeviceStableIds(dv), checksum:String(b?.integrity?.payloadHash||''), eventLedgerHead:String(b?.integrity?.eventLedgerHead||b?.revision?.eventLedgerHead||''), eventLedgerSeq:Number(b?.integrity?.eventLedgerSeq||b?.revision?.eventLedgerSeq||0), eventLedgerDeviceStableId:String(b?.integrity?.eventLedgerDeviceStableId||b?.revision?.eventLedgerDeviceStableId||''), archivableLedgerHead:String(b?.integrity?.archivableLedgerHead||b?.revision?.archivableLedgerHead||''), archivableLedgerSeq:Number(b?.integrity?.archivableLedgerSeq||b?.revision?.archivableLedgerSeq||0), archivableLedgerDeviceStableId:String(b?.integrity?.archivableLedgerDeviceStableId||b?.revision?.archivableLedgerDeviceStableId||''), archivableLedgerChainId:String(b?.integrity?.archivableLedgerChainId||b?.revision?.archivableLedgerChainId||''), archivableEventCount:Number(b?.integrity?.archivableEventCount||b?.revision?.archivableEventCount||0), eventLogHash:String(b?.integrity?.eventLogHash||b?.revision?.eventLogHash||''), sharedStorageHash:String(b?.integrity?.sharedStorageHash||b?.revision?.sharedStorageHash||''), version:String(b?.version||b?.revision?.version||'unknown'), sourceDeviceStableId:String(b?.revision?.sourceDeviceStableId||''), sourceDeviceLabel:String(b?.revision?.sourceDeviceLabel||''), sourceDeviceClass:String(b?.revision?.sourceDeviceClass||''), sourcePlatform:String(b?.revision?.sourcePlatform||'') }); }
}
