// UID.001_(Playback safety invariant)_(не допустить скрытых остановок плеера)_(intel-слой ничего не стопает и не сбрасывает без явного действия пользователя)
// UID.002_(UID-first core)_(сделать uid единым ключом всей системы)_(все связи track/listener/recs/sync строить только по uid)
// UID.003_(Event log truth)_(иметь честную восстанавливаемую историю)_(долгие пользовательские состояния выводить из событий, а не из UI)
// UID.004_(Stats as cache)_(ускорить интерфейс без потери правды)_(агрегаты считать кэшем над event log)
// UID.005_(Soft-disable intel layer)_(не парализовать плеер при проблемах нового слоя)_(ввести флаг отключения через config/localStorage и no-op bootstrap)
// UID.006_(Lazy full semantic loading)_(не перегружать startup и mobile)_(грузить полные профили только по запросу)
// UID.007_(Local-first compute)_(снизить зависимость от облака и стоимость)_(максимум вычислений и кэшей держать на устройстве)
// UID.008_(No playback mutation by intel)_(сохранить стабильность очереди и позиции)_(intel-слой только читает, объясняет, рекомендует и рендерит)
// UID.009_(GitHub-first additive rollout)_(внедрять живьём без больших рефакторингов)_(добавлять новые файлы и мягкие точки интеграции)
// UID.010_(Manual presentation overrides)_(разрешить править любую карточку трека вручную)_(отделить presentation от raw/final analysis)
// UID.011_(Media variants registry)_(расширить контентную модель трека)_(учитывать audio/minus/stems/clip/short/lossless как системные варианты)
// UID.012_(Quality dimension)_(учитывать Hi/Lo/Lossless в логике и аналитике)_(вести quality stats и quality-aware cache/resolution)
// UID.013_(Minus mode)_(поддержать караоке и отдельную аналитику)_(считать minus полноправным вариантом трека)
// UID.014_(Stems mode)_(поддержать раздельные дорожки и future mix flows)_(хранить stems как feature-capable variant)
// UID.015_(Clip/short variants)_(отделить просмотр видео от прослушивания)_(вести clip/short как отдельные типы контента и событий)
// UID.016_(Feature flags on track)_(быстро понимать возможности трека)_(добавить hasLyrics/hasMinus/hasStems/hasClip/hasShort/hasLossless/profile flags)
// UID.017_(Launch source stats)_(понять discovery surface и UX входов)_(собирать fromAlbum/fromFavorites/fromSearch/fromRecommendations/fromPlaylist/fromHistory)
// UID.018_(Variant and quality stats)_(видеть реальные режимы потребления)_(вести per-uid variantStats и qualityStats)
// UID.019_(Compact TrackProfile index)_(быстро фильтровать и рекомендовать каталог)_(держать легкий index в data/track-profiles-index.json)
// UID.020_(Full TrackProfile per uid)_(открывать детальную карточку песни)_(держать по одному JSON на трек в data/track-profiles/)
// UID.021_(musicAnalysis block)_(описывать звучание)_(хранить bpm/key/dynamics/timbre/energy/audio-embeddings и audio similarity)
// UID.022_(lyricAnalysis block)_(описывать смысл текста)_(хранить summary/keywords/quotes/scenes/narrative/entities/tags/axes/warnings)
// UID.023_(finalProfile block)_(иметь единую fused truth для рекомендаций и карточек)_(сливать audio+lyrics+curation в один профиль)
// UID.024_(Strict taxonomy-v2)_(избежать зоопарка тегов)_(использовать только канонические keys genres/styles/moods/themes/use_cases/events/axes/warnings)
// UID.025_(Weighted tags 0..1)_(получить тонкие фильтры и ранжирование)_(хранить веса вместо грубых boolean-тегов)
// UID.026_(Genres/styles/moods/themes/use_cases/events)_(охватить музыку и жизненный контекст)_(классифицировать трек по нескольким смысловым осям)
// UID.027_(Continuous axes)_(строить координаты для реков)_(использовать energy/valence/arousal/melancholy/socialness/humor/storytelling и др.)
// UID.028_(Content warnings)_(делать безопасные рекомендации и family mode)_(хранить explicit/violence/self_harm/horror/war/psychological_distress)
// UID.029_(Keywords layer)_(искать и связывать треки по образам)_(извлекать слова и фразы с type+probability)
// UID.030_(Quotes layer)_(давать яркие цитаты для UI и sharing)_(хранить 0..3 короткие репрезентативные строки)
// UID.031_(Scenes layer)_(показывать сюжет песни)_(хранить последовательность сцен с what_happens и mood)
// UID.032_(Narrative layer)_(понимать кто и как говорит в песне)_(хранить person/addressing/tone profile)
// UID.033_(Entities layer)_(связывать песни по персонажам/местам/символам)_(извлекать characters/places/objects/symbols)
// UID.034_(Track relations graph)_(уметь делать recs не только по similar_tracks)_(развести audio_similarity/theme_similarity/mood_similarity/transition_fit/complementary_pair)
// UID.035_(Similar tracks)_(дать быстрый блок похожих песен)_(хранить top-related uid list в профиле и индексе)
// UID.036_(Track presentation layer)_(сделать карточки редактируемыми и стабильными)_(хранить hook/tagline/mini-description/hero-quote/badges/chips отдельно)
// UID.037_(Card overrides)_(разрешить редакторские правки без ломки анализа)_(подмешивать presentation override поверх finalProfile)
// UID.038_(Track profile modal)_(показывать подробный паспорт трека в UI)_(делать отдельную модалку вместо раздувания statistics-modal)
// UID.039_(Share cards from profile)_(делать карточки умными и красивыми)_(ShareGenerator должен уметь брать summary/badges/reasons/presentation)
// UID.040_(Semantic search hooks)_(искать по смыслу, а не только по строке)_(использовать keywords/themes/moods/entities/lyrics index и future NL search)
// UID.041_(Showcase semantic filters)_(сделать витрину центром discovery)_(добавить фильтры по moods/themes/styles/use_cases/events/seasonality)
// UID.042_(Showcase semantic sorting)_(давать новые способы просмотра каталога)_(сортировать по axes: energy/melancholy/humor/storytelling/family_friendly и др.)
// UID.043_(Smart playlists)_(строить сценарные подборки)_(генерировать блоки типа night/driving/protest/fairytale/wedding/crying/kids)
// UID.044_(ListenerProfile core)_(понимать вкус пользователя как сущность)_(строить отдельный профиль слушателя поверх stats/events/favorites)
// UID.045_(Tag preferences)_(знать любимые жанры/темы/настроения)_(агрегировать preference-веса по taxonomy-группам)
// UID.046_(Axis preferences)_(знать любимую эмоциональную геометрию)_(агрегировать средние и доминирующие axes пользователя)
// UID.047_(Feature affinity)_(понимать продуктовые привычки пользователя)_(считать склонность к lyrics/stems/minus/clip/lossless/sleep timer и др.)
// UID.048_(Time profile)_(учитывать когда пользователь слушает)_(строить morning/day/evening/night и weekday/weekend профили)
// UID.049_(Behavior archetype)_(делать human-readable портрет слушателя)_(выводить repeater/explorer/album-listener/lyrics-focused/background-listener и др.)
// UID.050_(Session profile)_(понимать контекст текущего прослушивания)_(строить мягкий профиль сессии для next-track рекомендаций)
// UID.051_(Collection state)_(превратить трек в собираемый объект)_(вести per-uid освоение трека пользователем)
// UID.052_(Track badges and completion)_(дать коллекционный и геймификационный слой)_(слушал/любимое/lyrics used/clip watched/stems/minus/lossless/veteran/completion percent)
// UID.053_(Rediscovery engine)_(возвращать забытые любимые треки)_(сравнивать lastPlayedAt с favorite/full history и строить forgotten_hits)
// UID.054_(Recommendation engine core)_(перестать рекомендовать случайно)_(собрать единый движок поверх listener+track profiles)
// UID.055_(Recommendation strategies)_(легко добавлять новые типы подбора)_(держать отдельные scorer-модули вместо хаотичных if в UI)
// UID.056_(Recommendation reasons)_(объяснять почему показан трек)_(возвращать reason codes + human explanation)
// UID.057_(Audio similarity strategy)_(находить похожее по звуку)_(сравнивать embeddings/tempo/energy/timbre)
// UID.058_(Lyric and theme strategy)_(находить похожее по смыслу)_(сравнивать themes/keywords/scenes/narrative/entities)
// UID.059_(Mood/use-case/event/season strategy)_(подбирать по ситуации и настроению)_(сравнивать moods/use_cases/events/seasonality/time_of_day)
// UID.060_(Session-aware next-track strategy)_(подбирать следующий трек под текущий поток)_(учитывать session profile, current track, energy curve и sleep/night context)
// UID.061_(Community-driven recommendations)_(усилить recs сигналом похожих пользователей)_(использовать cohort/similar listeners/global aggregates)
// UID.062_(Recommendation memory and feedback)_(не повторять тупо одни и те же советы)_(хранить shown/clicked/accepted/dismissed/cooldowns)
// UID.063_(Profile recs tab upgrade)_(сделать вкладку Для Вас реально полезной)_(перевести её на recommendation engine и listener profile)
// UID.064_(Global track stats)_(понимать жизнь треков в аудитории)_(держать popularity/completion/replay/favorite/share/recommendation metrics)
// UID.065_(Cohort model)_(группировать пользователей по стилю поведения)_(ввести кластеры night listeners, lyrics lovers, collectors и др.)
// UID.066_(Similar listeners)_(строить слой похожих пользователей)_(хранить future similarity hooks и cohort affinity)
// UID.067_(User-vs-community compare)_(давать личные инсайты)_(сравнивать профиль слушателя с агрегированной нормой)
// UID.068_(Public playlist analytics)_(развить социальную часть каталога)_(считать views/saves/share conversions и reuse playlists)
// UID.069_(Internal user identity)_(сделать один профиль на все внешние входы)_(ввести internalUserId как канонический ключ пользователя)
// UID.070_(Linked providers)_(дать пользователю много внешних аккаунтов без конфликтов)_(подключать Yandex/Google/VK к одному internal profile)
// UID.071_(Provider capability model)_(понимать что умеет каждый провайдер)_(вести scopes/capabilities/roles вместо жесткого if-provider)
// UID.072_(Provider consents)_(контролировать доступы и приватность)_(хранить analytics/personalization/social/cloud/AI consent flags)
// UID.073_(Hybrid sync orchestrator)_(объединить несколько провайдеров вокруг одного профиля)_(ввести primary/mirror/social roles и единый sync state)
// UID.074_(Primary backup provider)_(иметь основной источник сохранения)_(по умолчанию делать Yandex основным backup channel)
// UID.075_(Secondary mirror backup)_(получить резервную копию и отказоустойчивость)_(держать Google как mirror backup option)
// UID.076_(Restore policy)_(сделать восстановление предсказуемым)_(идти primary -> secondary -> local merge через event logs)
// UID.077_(Yandex auth/backup/AI)_(использовать сильные стороны Яндекса)_(связать login/cloud/assistant/metrics в одном provider role)
// UID.078_(Google mirror/export)_(использовать сильные стороны Google без конфликта identity)_(дать mirror backup/export/future convenience actions)
// UID.079_(VK social/media actions)_(связать приложение с сообществом и API VK)_(готовить likes/comments/community/video/audio actions через capability bridge)
// UID.080_(Provider actions bridge)_(не размазывать внешние действия по UI)_(вести единый слой provider-actions с проверкой capability)
// UID.081_(Telemetry mapper)_(безопасно отправлять внешнюю аналитику)_(маппить локальные события в whitelisted external payloads)
// UID.082_(Local truth vs external telemetry split)_(не смешивать приватную правду и продуктовые метрики)_(raw data хранить локально, наружу отдавать только mapped layer)
// UID.083_(Yandex Metrica safe export)_(получать пользу от метрики без утечек)_(отправлять screens/recs/shares/sync/auth/provider events по consent)
// UID.084_(AI content analysis)_(автоматизировать построение lyricAnalysis и card copy)_(использовать LLM по строгой taxonomy/schema)
// UID.085_(AI explanation layer)_(делать рекомендации и профиль понятными)_(строить explanation text поверх reasons и listener/track profile)
// UID.086_(AI natural-language assistant)_(дать поиск и подборки обычным языком)_(готовить future слой NL search/filter/recommendation)
// UID.087_(CI validators for profiles)_(не пускать мусор в semantic слой)_(добавить schema/normalizer/validation hooks для track profiles)
// UID.088_(Profiles data layout)_(не раздувать старт приложения)_(держать index отдельно от full profile directory)
// UID.089_(Future MetaDB stores)_(подготовить persistent контур для intel-слоя)_(добавить listener_profile/provider_identity/hybrid_sync/recommendation_state/collection_state)
// UID.090_(Service-worker caching for intel assets)_(сохранить offline resilience и быстрый boot)_(добавить intel scripts + profile index в core static cache)
// UID.091_(No-op stubs before full implementation)_(получить безопасный контур без риска для текущего плеера)_(все новые модули сделать валидными и мягкими заглушками)
// UID.092_(Incremental rollout order)_(внедрять по приоритету и без паралича)_(bootstrap -> profiles -> listener -> recs -> providers -> sync -> telemetry -> AI)
// UID.093_(Roadmap markers in touched files)_(не потерять идеи в длинной переписке)_(в начало новых и ключевых старых файлов добавить UID-строки как встроенное ТЗ)
// UID.094_(No-paralysis rule)_(оставить текущее приложение рабочим на каждом шаге)_(любой сбой intel-слоя должен только отключать intel-функции, но не ломать плеер)
export const INTEL_ROADMAP_VERSION = 'uid-roadmap-v1';
export default INTEL_ROADMAP_VERSION;
