// UID.001_(Playback safety invariant)_(boot не управляет playback кроме восстановления после доверенного жеста)
// UID.092_(Incremental rollout order)_(offline → analytics → intel → account → cloud → UI)
// UID.094_(No-paralysis rule)_(optional-модули падают мягко, критические менеджеры проверяются явно)
// UID.096_(Helper-first anti-duplication policy)_(единые boot/import/wait helpers без повторяющихся try/catch)

(function(W,D){'use strict';
const C=W.APP_CONFIG||{},$=id=>D.getElementById(id),click=id=>$(id)?.click(),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const soft=async(label,task,fallback=null)=>{try{return await task();}catch(error){console.warn(`[Boot:${label}]`,error?.message||error);return fallback;}};
const waitGlobal=async name=>{if(W.Utils?.waitFor)return W.Utils.waitFor(()=>typeof W[name]?.initialize==='function',3000);for(let i=0;i<30&&!W[name]?.initialize;i++)await sleep(100);return typeof W[name]?.initialize==='function';};
const requireGlobal=async name=>{if(!await waitGlobal(name))throw new Error(`boot_global_missing:${name}`);return W[name];};
const initGlobal=async name=>(await requireGlobal(name)).initialize?.();
const bindAchievementUi=PF=>{W.addEventListener('achievements:updated',event=>{const d=event.detail||{},engine=W.achievementEngine,total=Number.isFinite(Number(d.total))?Number(d.total):(engine?.achievements?.length||0),unlocked=Number.isFinite(Number(d.unlocked))?Number(d.unlocked):Object.keys(engine?.unlocked||{}).length,profile=d.profile||engine?.profile||null,count=$('achievementsCount'),fill=$('achievementsFill');if(count)count.textContent=`ВЫПОЛНЕНО: ${unlocked} / ${total}`;if(fill&&total)fill.style.width=`${unlocked/total*100}%`;if(profile){const level=$('user-level-badge'),iconLevel=$('pg-lvl-val'),xpFill=$('xp-progress-fill'),xpText=$('xp-text'),iconXp=$('pg-xp-cur'),currentXp=Math.pow(profile.level-1,2)*100,nextXp=Math.pow(profile.level,2)*100;if(level)level.textContent=profile.level;if(iconLevel)iconLevel.textContent=profile.level;if(xpFill)xpFill.style.width=`${Math.max(0,Math.min(100,(profile.xp-currentXp)/(nextXp-currentXp)*100))}%`;if(xpText)xpText.textContent=`${profile.xp} / ${nextXp} XP`;if(iconXp)iconXp.textContent=`${profile.xp} XP`;}const text=$('ach-hint-bubble-text');if(!text||!engine?.achievements)return;let goals=engine.achievements.filter(item=>!item.isUnlocked&&!item.isHidden&&(item.progressMeta||item.progress?.target>item.progress?.current)).sort((a,b)=>(b.progress?.pct||0)-(a.progress?.pct||0));const pwaIndex=goals.findIndex(item=>item.id==='pwa_installed');if(pwaIndex>=0&&!W.matchMedia('(display-mode: standalone)').matches&&!navigator.standalone)goals.unshift(goals.splice(pwaIndex,1)[0]);goals=goals.slice(0,3).map(PF.fmtAchBubbleText);clearInterval(W._bInt);let index=0;const update=()=>{if(!goals.length)return;text.style.opacity=0;setTimeout(()=>{text.innerHTML=goals[index++%goals.length];text.style.transform='scale(1)';text.style.opacity=1;requestAnimationFrame(()=>{const width=text.parentElement.clientWidth-36;if(text.scrollWidth>width)text.style.transform=`scale(${width/text.scrollWidth})`;});},300);};update();if(goals.length>1)W._bInt=setInterval(update,8000);});const bubble=$('ach-hint-bubble');if(bubble)bubble.onclick=()=>{sessionStorage.setItem('jumpToAch','1');W.AlbumsManager?.loadAlbum(C.SPECIAL_PROFILE_KEY||'__profile__');};};
const runMigration=async metaDB=>{const key='migration:cleanup_duplicates:v3';if(localStorage.getItem(key))return;const{default:DeviceRegistry}=await import('./analytics/device-registry.js'),before=DeviceRegistry.getDeviceRegistry(),after=DeviceRegistry.normalizeDeviceRegistry(before);if(after.length<before.length)DeviceRegistry.saveDeviceRegistry(after);const{cleanupWarmEventsStore}=await import('./analytics/backup-event-cleanup.js');await cleanupWarmEventsStore(metaDB);localStorage.setItem(key,String(Date.now()));};
const initOffline=async()=>{await import('./offline/net-policy.js').then(module=>module.initNetPolicy?.());await import('./app/offline-ui-bootstrap.js').then(module=>module.initOfflineUI?.());const manager=(await import('./offline/offline-manager.js')).default;await manager.initialize();await import('./offline/track-resolver.js').then(module=>module.initTrackResolver(manager));await import('./app/playback-cache-bootstrap.js').then(module=>module.initPlaybackCache?.());await import('./offline/update-checker.js').then(module=>module.initUpdateChecker?.());};
const initAnalytics=async()=>{const[M,L,ST,SA,AE,LS,PF]=await Promise.all([import('./analytics/meta-db.js'),import('./analytics/event-logger.js'),import('./analytics/session-tracker.js'),import('./analytics/stats-aggregator.js'),import('./analytics/achievement-engine.js'),import('./analytics/live-stats.js'),import('./ui/progress-formatters.js')]);await M.metaDB.init();await L.eventLogger.init();bindAchievementUi(PF);new ST.SessionTracker();W.statsAggregator=new SA.StatsAggregator();await LS.liveStatsTracker.initialize();W.achievementEngine=new AE.AchievementEngine();await soft('listening-receipts',()=>import('./analytics/listening-receipts.js').then(module=>module.listeningReceiptService?.initialize?.()));await soft('migration',()=>runMigration(M.metaDB));W.dispatchEvent(new CustomEvent('analytics:logUpdated'));};
const initAccountAndCloud=async()=>{await soft('yandex-auth',()=>import('./core/yandex-auth.js').then(module=>module.YandexAuth?.checkAutoRelogin?.()));await soft('account-vault',async()=>{const module=await import('./analytics/account-data-boundary.js');await module.initAccountDataBoundary?.();});await soft('favorite-mirror',()=>import('./analytics/favorite-mirror.js').then(module=>module.favoriteMirrorService?.initialize?.()));await soft('yandex-auto-sync',()=>import('./app/profile/yandex-auto-sync.js').then(module=>module.initYandexAutoSync?.()));await soft('backup-sync',()=>import('./analytics/backup-sync-engine.js').then(module=>module.initBackupSyncEngine?.()));};
const initRuntime=async()=>{await soft('offline',initOffline);await soft('analytics',initAnalytics);if(C.INTEL_LAYER_ENABLED!==false)await soft('intel',()=>import('./intel/bootstrap.js').then(module=>module.initIntelBootstrap?.({W,D,C})));await initAccountAndCloud();};
const initManagers=async()=>{await initGlobal('GalleryManager');await soft('showcase',()=>import('./app/showcase/index.js').then(module=>module.default?.initialize?.()));await initGlobal('AlbumsManager');await initGlobal('PlayerUI');await soft('playback-clock',()=>import('./app/player/playback-clock.js').then(module=>module.initPlaybackClock?.()));await soft('logo-pulse',()=>import('./ui/logo-pulse.js'));['SleepTimer','LyricsModal','SystemInfoManager'].forEach(name=>W[name]?.initialize?.());await soft('statistics-modal',()=>import('./ui/statistics-modal.js'));await soft('app-modals',()=>import('./ui/app-modals.js').then(module=>module.bindAppModals?.({W,D,config:C})));};
const bindShortcuts=()=>{const actions={k:()=>W.PlayerUI?.togglePlayPause?.(),' ':event=>{event.preventDefault();W.PlayerUI?.togglePlayPause?.();},n:'next',p:'prev',x:'stop',arrowleft:()=>W.playerCore?.seek?.(Math.max(0,(W.playerCore?.getPosition?.()||0)-5)),arrowright:()=>W.playerCore?.seek?.(Math.min(W.playerCore?.getDuration?.()||0,(W.playerCore?.getPosition?.()||0)+5)),arrowup:event=>{event.preventDefault();W.playerCore?.setVolume?.(Math.min(100,(W.playerCore?.getVolume?.()||0)+5));},arrowdown:event=>{event.preventDefault();W.playerCore?.setVolume?.(Math.max(0,(W.playerCore?.getVolume?.()||0)-5));},m:'mute-btn',r:'repeat-btn',u:'shuffle-btn',a:'animation-btn',b:'pulse-btn',f:'favorites-btn',y:'lyrics-toggle-btn',t:()=>W.SleepTimer?.show?.()};D.addEventListener('keydown',event=>{if(['INPUT','TEXTAREA','SELECT'].includes(event.target?.tagName)||event.target?.isContentEditable)return;const action=actions[event.key.toLowerCase()];if(typeof action==='function')action(event);else if(typeof action==='string'&&typeof W.playerCore?.[action]==='function')W.playerCore[action]();else if(typeof action==='string')click(action);});};
const bindPwa=()=>{let prompt=null;const button=$('install-pwa-btn'),standalone=W.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(standalone&&button)button.style.display='none';W.addEventListener('beforeinstallprompt',event=>{event.preventDefault();prompt=event;});if(button&&!standalone)button.onclick=async()=>{if(prompt){prompt.prompt();if((await prompt.userChoice).outcome==='accepted'){W.NotificationSystem?.success?.('Установка началась!');button.style.display='none';}prompt=null;return;}if(W.Utils?.getPlatform?.().isIOS){const box=D.createElement('div');box.className='ios-install-prompt';box.innerHTML='<button class="ios-prompt-close" type="button">×</button><img class="ios-prompt-icon" src="icons/apple-touch-icon.png" alt=""><div class="ios-prompt-title">Установить на iPhone</div><div class="ios-prompt-text">Нажмите <strong>Поделиться</strong> ↗️ в меню браузера,<br>а затем выберите <strong>«На экран Домой»</strong></div><button class="ios-prompt-button" type="button">Понятно</button>';box.onclick=event=>{if(event.target.closest('button')){box.classList.remove('show');setTimeout(()=>box.remove(),350);}};D.body.appendChild(box);requestAnimationFrame(()=>box.classList.add('show'));return;}W.NotificationSystem?.info?.('Установите через меню браузера');};W.addEventListener('appinstalled',()=>{W.NotificationSystem?.success?.('Успешно установлено!');if(button)button.style.display='none';W.eventLogger?.log?.('FEATURE_USED','global',{feature:'pwa_installed'});W.dispatchEvent(new CustomEvent('analytics:forceFlush'));});$('social-links')?.addEventListener('click',event=>{const link=event.target.closest?.('a');if(!link||!W.eventLogger)return;const href=String(link.getAttribute('href')||'').toLowerCase(),target=href.includes('youtube.com')||href.includes('youtu.be')?'youtube':href.includes('t.me')?'telegram':href.includes('vk.com')?'vk':href.includes('tiktok.com')?'tiktok':'other';W.eventLogger.log('FEATURE_USED','global',{feature:'social_visit',target});W.dispatchEvent(new CustomEvent('analytics:forceFlush'));});};
const openDeepLink=async raw=>{try{const url=new URL(raw||W.location.href,W.location.href),params=url.searchParams,game=!!(params.get('gcGame')||params.get('game')||params.get('join')),friends=!!(params.get('openFriends')||params.get('addFriend')||params.get('chatWith')||params.get('voiceWith'));if(!game&&!friends)return false;await W.AlbumsManager?.loadAlbum?.(game?(C.SPECIAL_GAMES_KEY||W.SPECIAL_GAMES_KEY||'__games__'):(C.SPECIAL_FRIENDS_KEY||W.SPECIAL_FRIENDS_KEY||'__friends__'));return true;}catch{return false;}};
const bindServiceWorkerMessages=()=>{if(!('serviceWorker'in navigator))return;const handler=event=>{const data=event.data||{};if(data.type==='SW_VERSION'){const version=String(data.version||'').trim();if(version&&version!==String(W.VERSION||''))W.ServiceWorkerManager?.handleVersionMessage?.({swVer:version});return;}if(data.type==='PUSH_NOTIFICATION_CLICK')openDeepLink(data.url);};navigator.serviceWorker.addEventListener('message',handler);W.addEventListener('message',handler);};
const restorePlayerState=async()=>{let state=null;try{state=JSON.parse(localStorage.getItem('playerStateV2')||'null');}catch{}if(!state?.trackUid||!state?.album||Date.now()-Number(state.ts||0)>43200000)return false;try{await W.TrackRegistry?.ensurePopulated?.();const list=W.PlaybackContextSource?.getSourcePlaylistForContext?.(state.album)||[],uid=String(state.trackUid||'').trim(),index=list.findIndex(track=>String(track?.uid||'').trim()===uid);if(!list.length||index<0)return false;if(W.AlbumsManager?.getPlayingAlbum?.()!==state.album)W.AlbumsManager?.setPlayingAlbum?.(state.album);if(state.currentAlbum)await W.AlbumsManager?.loadAlbum?.(state.currentAlbum).catch(()=>{});if(Number.isFinite(Number(state.volume))){const volume=Math.max(0,Math.min(100,Number(state.volume)));localStorage.setItem('playerVolume',String(volume));try{W.Howler?.volume?.(state.muted?0:volume/100);}catch{}}if('muted'in state)W.playerCore.flags.mute=!!state.muted;if(state.quality)W.playerCore.qMode=String(state.quality).toLowerCase()==='lo'?'lo':'hi';W.playerCore.flags.rep=!!state.repeat;W.playerCore.flags.shuf=!!state.shuffle;W.playerCore.setPlaylist(list,index,null,{preserveOriginalPlaylist:false,preserveShuffleMode:true,deferLoad:true});await W.playerCore.load(index,{autoPlay:false,resumePosition:Math.max(0,Number(state.position)||0),dir:1});if(state.wasPlaying){const events=['pointerdown','touchend','keydown'];let armed=true;const cleanup=()=>events.forEach(name=>D.removeEventListener(name,resume,true));const resume=event=>{if(!armed||event?.isTrusted===false)return;armed=false;cleanup();if(W.playerCore?.getCurrentTrackUid?.()===uid&&!W.playerCore?.isPlaying?.()){W.playerCore.prepareContext?.();W.playerCore.play?.();}};events.forEach(name=>D.addEventListener(name:data-switched', () => {
        this.lastFullListens.clear();
        this.session = { favOrderedRun: 0, favOrderedLastUid: null, favShuffleEvents: new Set(), midnightTripleTrack: null, midnightTripleCount: 0, lastFullUid: null };
      });
    }
