// UID.043_(Smart playlists)_(сделать плейлисты важной discovery-сущностью)_(showcase playlists остаются UI/store слоем, а semantic генерация позже приходит извне) UID.061_(Community-driven recommendations)_(готовить будущие community/shared playlist сценарии)_(плейлисты смогут становиться surface для cohort/similar-listener подборок, но не считать их сами) UID.068_(Public playlist analytics)_(развить публичные плейлисты как социальный объект)_(views/saves/share/import analytics должны сходиться сюда как UI touchpoint) UID.080_(Provider actions bridge)_(не смешивать sharing/community provider actions с playlist store)_(внешние social/provider действия должны идти через bridge, не прямо из playlist state) UID.082_(Local truth vs external telemetry split)_(не смешивать локальное состояние плейлиста и внешнюю аналитику)_(наружу только mapper-safe события, локально — только playlist truth) UID.094_(No-paralysis rule)_(плейлисты обязаны работать без intel/community/providers)_(любой social/semantic upgrade поверх них строго optional)
export const renderShowcasePlaylists = ({ actionsRoot: aR, listRoot: lR, activeId: aI, playlists: p, isDefaultId: iD, esc }) => {
  if (!aR || !lR) return;
  aR.innerHTML = `<button class="sc-pl-action ${iD(aI) ? 'active' : ''}" id="sc-pl-all">Все треки</button><button class="sc-pl-action" id="sc-pl-pst" title="Вставить ссылку">📋</button>`;
  lR.innerHTML = p.length ? p.map(x => `<div class="sc-pl-row ${aI === x.id ? 'active' : ''}" data-pid="${x.id}" ${x.color ? `style="--pl-color:${x.color};"` : ''}><div class="sc-pl-left"><span class="sc-pl-dot"></span><span class="sc-pl-title" title="${esc(x.name)}">${esc(x.name)}</span></div><div class="sc-pl-right"><button class="sc-pl-btn" data-act="rename" data-pid="${x.id}" title="Переименовать">✏️</button><button class="sc-pl-btn" data-act="shr" data-pid="${x.id}" title="Поделиться">🔗</button><button class="sc-pl-btn" data-act="col" data-pid="${x.id}" title="Цвет">🎨</button><button class="sc-pl-btn danger" data-act="del" data-pid="${x.id}" title="Удалить">✖</button></div></div>`).join('') : '<div class="sc-pl-empty">Плейлистов пока нет</div>';
};
export const renameShowcasePlaylist = ({ id: i, store: s, promptName: pN, onDone: oD }) => { const p = s.get(i); if (p) pN?.({ title: 'Переименовать', value: p.name, btnText: 'Сохранить', onSubmit: v => { p.name = v; s.save(p); oD?.(p); } }); };
export const shareShowcasePlaylist = ({ id: i, store: s, origin: o, pathname: ph, notify: n }) => { const p = s.get(i); if (p) { const u = `${o}${ph}?playlist=${btoa(unescape(encodeURIComponent(JSON.stringify({ v: 1, n: p.name, u: p.order || [] }))))}`; navigator.share ? navigator.share({ title: p.name, url: u }).catch(()=>{}) : navigator.clipboard.writeText(u).then(() => n?.success?.('Ссылка скопирована!')); } };
export const createShowcasePlaylist = ({ uids: u, fromEdit: fE = false, name: n = '', draft: d = null, store: s, mkPl: mP, trk: t, setActive: sA, clearUi: cU, renderTab: rT, notify: nf, promptName: pN }) => {
  const use = (u || []).filter(t); if (!use.length) return nf?.warning?.('Отметьте нужные треки чекбоксами');
  const done = nm => { const id = Date.now().toString(36); s.save(mP({ id, name: nm, order: [...use], hidden: fE && d ? use.filter(x => d.hid.has(x)) : [] })); cU?.(); sA?.(id); rT?.(); nf?.success?.(`Плейлист «${nm}» создан`); };
  n ? done(n) : pN?.({ title: 'Новый плейлист', value: `Мой плейлист ${s.pl().length + 1}`, btnText: 'Создать', onSubmit: done });
};
export default { renderShowcasePlaylists, renameShowcasePlaylist, shareShowcasePlaylist, createShowcasePlaylist };
